- hosts: triang
  remote_user: root
  tasks:
  - name: copy multitriangulation programm to hosts
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      mode: "{{item.mode}}"
    with_items:
      - { src: '~/Projects/multilateral_triangulation/catkin/devel/lib/triangulation/triangulation',dest: '~', mode: '0777'}
      - { src: '~/Projects/multilateral_triangulation/Quartus/output_files/soc_system.rbf',dest: '/mnt/mp1/soc_system.rbf', mode: '0777'}

