	MKRVIDOR4000_peripherals_lite_sys u0 (
		.clk_clk           (<connected-to-clk_clk>),           //       clk.clk
		.clk_0_clk         (<connected-to-clk_0_clk>),         //     clk_0.clk
		.encoder_encoder_a (<connected-to-encoder_encoder_a>), //   encoder.encoder_a
		.encoder_encoder_b (<connected-to-encoder_encoder_b>), //          .encoder_b
		.flash_spi_MOSI    (<connected-to-flash_spi_MOSI>),    // flash_spi.MOSI
		.flash_spi_SCLK    (<connected-to-flash_spi_SCLK>),    //          .SCLK
		.flash_spi_MISO    (<connected-to-flash_spi_MISO>),    //          .MISO
		.flash_spi_CS      (<connected-to-flash_spi_CS>),      //          .CS
		.i2c0_scl_i        (<connected-to-i2c0_scl_i>),        //      i2c0.scl_i
		.i2c0_scl_o        (<connected-to-i2c0_scl_o>),        //          .scl_o
		.i2c0_scl_en       (<connected-to-i2c0_scl_en>),       //          .scl_en
		.i2c0_sda_i        (<connected-to-i2c0_sda_i>),        //          .sda_i
		.i2c0_sda_o        (<connected-to-i2c0_sda_o>),        //          .sda_o
		.i2c0_sda_en       (<connected-to-i2c0_sda_en>),       //          .sda_en
		.i2c1_scl_i        (<connected-to-i2c1_scl_i>),        //      i2c1.scl_i
		.i2c1_scl_o        (<connected-to-i2c1_scl_o>),        //          .scl_o
		.i2c1_scl_en       (<connected-to-i2c1_scl_en>),       //          .scl_en
		.i2c1_sda_i        (<connected-to-i2c1_sda_i>),        //          .sda_i
		.i2c1_sda_o        (<connected-to-i2c1_sda_o>),        //          .sda_o
		.i2c1_sda_en       (<connected-to-i2c1_sda_en>),       //          .sda_en
		.i2c2_scl_i        (<connected-to-i2c2_scl_i>),        //      i2c2.scl_i
		.i2c2_scl_o        (<connected-to-i2c2_scl_o>),        //          .scl_o
		.i2c2_scl_en       (<connected-to-i2c2_scl_en>),       //          .scl_en
		.i2c2_sda_i        (<connected-to-i2c2_sda_i>),        //          .sda_i
		.i2c2_sda_o        (<connected-to-i2c2_sda_o>),        //          .sda_o
		.i2c2_sda_en       (<connected-to-i2c2_sda_en>),       //          .sda_en
		.i2c3_scl_i        (<connected-to-i2c3_scl_i>),        //      i2c3.scl_i
		.i2c3_scl_o        (<connected-to-i2c3_scl_o>),        //          .scl_o
		.i2c3_scl_en       (<connected-to-i2c3_scl_en>),       //          .scl_en
		.i2c3_sda_i        (<connected-to-i2c3_sda_i>),        //          .sda_i
		.i2c3_sda_o        (<connected-to-i2c3_sda_o>),        //          .sda_o
		.i2c3_sda_en       (<connected-to-i2c3_sda_en>),       //          .sda_en
		.mb_ak             (<connected-to-mb_ak>),             //        mb.ak
		.mb_rq             (<connected-to-mb_rq>),             //          .rq
		.nina_spi_MOSI     (<connected-to-nina_spi_MOSI>),     //  nina_spi.MOSI
		.nina_spi_SCLK     (<connected-to-nina_spi_SCLK>),     //          .SCLK
		.nina_spi_MISO     (<connected-to-nina_spi_MISO>),     //          .MISO
		.nina_spi_CS       (<connected-to-nina_spi_CS>),       //          .CS
		.pex_pio_in        (<connected-to-pex_pio_in>),        //   pex_pio.in
		.pex_pio_dir       (<connected-to-pex_pio_dir>),       //          .dir
		.pex_pio_out       (<connected-to-pex_pio_out>),       //          .out
		.pex_pio_msel      (<connected-to-pex_pio_msel>),      //          .msel
		.pixel_data        (<connected-to-pixel_data>),        //     pixel.data
		.pixel_clock       (<connected-to-pixel_clock>),       //          .clock
		.qspi_dclk         (<connected-to-qspi_dclk>),         //      qspi.dclk
		.qspi_ncs          (<connected-to-qspi_ncs>),          //          .ncs
		.qspi_oe           (<connected-to-qspi_oe>),           //          .oe
		.qspi_dataout      (<connected-to-qspi_dataout>),      //          .dataout
		.qspi_dataoe       (<connected-to-qspi_dataoe>),       //          .dataoe
		.qspi_datain       (<connected-to-qspi_datain>),       //          .datain
		.reset_reset_n     (<connected-to-reset_reset_n>),     //     reset.reset_n
		.reset_0_reset_n   (<connected-to-reset_0_reset_n>),   //   reset_0.reset_n
		.sam_pio_in        (<connected-to-sam_pio_in>),        //   sam_pio.in
		.sam_pio_dir       (<connected-to-sam_pio_dir>),       //          .dir
		.sam_pio_out       (<connected-to-sam_pio_out>),       //          .out
		.sam_pio_msel      (<connected-to-sam_pio_msel>),      //          .msel
		.sam_pwm_pwm       (<connected-to-sam_pwm_pwm>),       //   sam_pwm.pwm
		.sdram_addr        (<connected-to-sdram_addr>),        //     sdram.addr
		.sdram_ba          (<connected-to-sdram_ba>),          //          .ba
		.sdram_cas_n       (<connected-to-sdram_cas_n>),       //          .cas_n
		.sdram_cke         (<connected-to-sdram_cke>),         //          .cke
		.sdram_cs_n        (<connected-to-sdram_cs_n>),        //          .cs_n
		.sdram_dq          (<connected-to-sdram_dq>),          //          .dq
		.sdram_dqm         (<connected-to-sdram_dqm>),         //          .dqm
		.sdram_ras_n       (<connected-to-sdram_ras_n>),       //          .ras_n
		.sdram_we_n        (<connected-to-sdram_we_n>),        //          .we_n
		.spi0_MOSI         (<connected-to-spi0_MOSI>),         //      spi0.MOSI
		.spi0_SCLK         (<connected-to-spi0_SCLK>),         //          .SCLK
		.spi0_MISO         (<connected-to-spi0_MISO>),         //          .MISO
		.spi0_CS           (<connected-to-spi0_CS>),           //          .CS
		.spi1_MOSI         (<connected-to-spi1_MOSI>),         //      spi1.MOSI
		.spi1_SCLK         (<connected-to-spi1_SCLK>),         //          .SCLK
		.spi1_MISO         (<connected-to-spi1_MISO>),         //          .MISO
		.spi1_CS           (<connected-to-spi1_CS>),           //          .CS
		.spi2_MOSI         (<connected-to-spi2_MOSI>),         //      spi2.MOSI
		.spi2_SCLK         (<connected-to-spi2_SCLK>),         //          .SCLK
		.spi2_MISO         (<connected-to-spi2_MISO>),         //          .MISO
		.spi2_CS           (<connected-to-spi2_CS>),           //          .CS
		.spi3_MOSI         (<connected-to-spi3_MOSI>),         //      spi3.MOSI
		.spi3_SCLK         (<connected-to-spi3_SCLK>),         //          .SCLK
		.spi3_MISO         (<connected-to-spi3_MISO>),         //          .MISO
		.spi3_CS           (<connected-to-spi3_CS>),           //          .CS
		.spi4_MOSI         (<connected-to-spi4_MOSI>),         //      spi4.MOSI
		.spi4_SCLK         (<connected-to-spi4_SCLK>),         //          .SCLK
		.spi4_MISO         (<connected-to-spi4_MISO>),         //          .MISO
		.spi4_CS           (<connected-to-spi4_CS>),           //          .CS
		.wm_pio_in         (<connected-to-wm_pio_in>),         //    wm_pio.in
		.wm_pio_dir        (<connected-to-wm_pio_dir>),        //          .dir
		.wm_pio_out        (<connected-to-wm_pio_out>),        //          .out
		.wm_pio_msel       (<connected-to-wm_pio_msel>)        //          .msel
	);

