// Generated by gencpp from file triangulation_msg/mode_msg.msg
// DO NOT EDIT!


#ifndef TRIANGULATION_MSG_MESSAGE_MODE_MSG_H
#define TRIANGULATION_MSG_MESSAGE_MODE_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace triangulation_msg
{
template <class ContainerAllocator>
struct mode_msg_
{
  typedef mode_msg_<ContainerAllocator> Type;

  mode_msg_()
    : id(0)
    , mode(false)
    , sync_mode(false)
    , sync_enable(false)  {
    }
  mode_msg_(const ContainerAllocator& _alloc)
    : id(0)
    , mode(false)
    , sync_mode(false)
    , sync_enable(false)  {
  (void)_alloc;
    }



   typedef uint8_t _id_type;
  _id_type id;

   typedef uint8_t _mode_type;
  _mode_type mode;

   typedef uint8_t _sync_mode_type;
  _sync_mode_type sync_mode;

   typedef uint8_t _sync_enable_type;
  _sync_enable_type sync_enable;





  typedef boost::shared_ptr< ::triangulation_msg::mode_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::triangulation_msg::mode_msg_<ContainerAllocator> const> ConstPtr;

}; // struct mode_msg_

typedef ::triangulation_msg::mode_msg_<std::allocator<void> > mode_msg;

typedef boost::shared_ptr< ::triangulation_msg::mode_msg > mode_msgPtr;
typedef boost::shared_ptr< ::triangulation_msg::mode_msg const> mode_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::triangulation_msg::mode_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::triangulation_msg::mode_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace triangulation_msg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'triangulation_msg': ['/home/sausy/Projects/multilateral_triangulation/catkin/src/triang_communication/triangulation_msg/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::triangulation_msg::mode_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::triangulation_msg::mode_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::triangulation_msg::mode_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::triangulation_msg::mode_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::triangulation_msg::mode_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::triangulation_msg::mode_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::triangulation_msg::mode_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e2e08abfaa655bc1b5e56f4201c7cfe0";
  }

  static const char* value(const ::triangulation_msg::mode_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe2e08abfaa655bc1ULL;
  static const uint64_t static_value2 = 0xb5e56f4201c7cfe0ULL;
};

template<class ContainerAllocator>
struct DataType< ::triangulation_msg::mode_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "triangulation_msg/mode_msg";
  }

  static const char* value(const ::triangulation_msg::mode_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::triangulation_msg::mode_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 id\n"
"#0 master broadcast, 1 slave broadcast\n"
"bool mode\n"
"#0 sync slave,       1 sync master\n"
"bool sync_mode\n"
"bool sync_enable\n"
;
  }

  static const char* value(const ::triangulation_msg::mode_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::triangulation_msg::mode_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.mode);
      stream.next(m.sync_mode);
      stream.next(m.sync_enable);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mode_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::triangulation_msg::mode_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::triangulation_msg::mode_msg_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
    s << indent << "sync_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sync_mode);
    s << indent << "sync_enable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sync_enable);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRIANGULATION_MSG_MESSAGE_MODE_MSG_H
