// Generated by gencpp from file triangulation_msg/time_sync_msg.msg
// DO NOT EDIT!


#ifndef TRIANGULATION_MSG_MESSAGE_TIME_SYNC_MSG_H
#define TRIANGULATION_MSG_MESSAGE_TIME_SYNC_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace triangulation_msg
{
template <class ContainerAllocator>
struct time_sync_msg_
{
  typedef time_sync_msg_<ContainerAllocator> Type;

  time_sync_msg_()
    : id(0)
    , sync_time_div()
    , time_div()
    , sys_time()  {
    }
  time_sync_msg_(const ContainerAllocator& _alloc)
    : id(0)
    , sync_time_div(_alloc)
    , time_div(_alloc)
    , sys_time(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _id_type;
  _id_type id;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _sync_time_div_type;
  _sync_time_div_type sync_time_div;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _time_div_type;
  _time_div_type time_div;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _sys_time_type;
  _sys_time_type sys_time;





  typedef boost::shared_ptr< ::triangulation_msg::time_sync_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::triangulation_msg::time_sync_msg_<ContainerAllocator> const> ConstPtr;

}; // struct time_sync_msg_

typedef ::triangulation_msg::time_sync_msg_<std::allocator<void> > time_sync_msg;

typedef boost::shared_ptr< ::triangulation_msg::time_sync_msg > time_sync_msgPtr;
typedef boost::shared_ptr< ::triangulation_msg::time_sync_msg const> time_sync_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::triangulation_msg::time_sync_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::triangulation_msg::time_sync_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace triangulation_msg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'triangulation_msg': ['/home/roboy/BikeToRikshaw/old_git_stuff/multilateral_triangulation/catkin/src/triang_communication/triangulation_msg/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::triangulation_msg::time_sync_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::triangulation_msg::time_sync_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::triangulation_msg::time_sync_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::triangulation_msg::time_sync_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::triangulation_msg::time_sync_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::triangulation_msg::time_sync_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::triangulation_msg::time_sync_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8fc40ceccbea84cbac12bd27ca06f4f3";
  }

  static const char* value(const ::triangulation_msg::time_sync_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8fc40ceccbea84cbULL;
  static const uint64_t static_value2 = 0xac12bd27ca06f4f3ULL;
};

template<class ContainerAllocator>
struct DataType< ::triangulation_msg::time_sync_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "triangulation_msg/time_sync_msg";
  }

  static const char* value(const ::triangulation_msg::time_sync_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::triangulation_msg::time_sync_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 id\n\
float32[] sync_time_div\n\
float32[] time_div\n\
float32[] sys_time\n\
";
  }

  static const char* value(const ::triangulation_msg::time_sync_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::triangulation_msg::time_sync_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.sync_time_div);
      stream.next(m.time_div);
      stream.next(m.sys_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct time_sync_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::triangulation_msg::time_sync_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::triangulation_msg::time_sync_msg_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "sync_time_div[]" << std::endl;
    for (size_t i = 0; i < v.sync_time_div.size(); ++i)
    {
      s << indent << "  sync_time_div[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.sync_time_div[i]);
    }
    s << indent << "time_div[]" << std::endl;
    for (size_t i = 0; i < v.time_div.size(); ++i)
    {
      s << indent << "  time_div[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.time_div[i]);
    }
    s << indent << "sys_time[]" << std::endl;
    for (size_t i = 0; i < v.sys_time.size(); ++i)
    {
      s << indent << "  sys_time[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.sys_time[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRIANGULATION_MSG_MESSAGE_TIME_SYNC_MSG_H
