# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from triangulation_msg/system_ctl.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class system_ctl(genpy.Message):
  _md5sum = "b2402184671eaa4cfe66017f90187544"
  _type = "triangulation_msg/system_ctl"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint8 master_id
bool enable_slave_input
float32[] trigger_time
"""
  __slots__ = ['master_id','enable_slave_input','trigger_time']
  _slot_types = ['uint8','bool','float32[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       master_id,enable_slave_input,trigger_time

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(system_ctl, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.master_id is None:
        self.master_id = 0
      if self.enable_slave_input is None:
        self.enable_slave_input = False
      if self.trigger_time is None:
        self.trigger_time = []
    else:
      self.master_id = 0
      self.enable_slave_input = False
      self.trigger_time = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2B().pack(_x.master_id, _x.enable_slave_input))
      length = len(self.trigger_time)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.pack(pattern, *self.trigger_time))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 2
      (_x.master_id, _x.enable_slave_input,) = _get_struct_2B().unpack(str[start:end])
      self.enable_slave_input = bool(self.enable_slave_input)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.trigger_time = struct.unpack(pattern, str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2B().pack(_x.master_id, _x.enable_slave_input))
      length = len(self.trigger_time)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.trigger_time.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 2
      (_x.master_id, _x.enable_slave_input,) = _get_struct_2B().unpack(str[start:end])
      self.enable_slave_input = bool(self.enable_slave_input)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.trigger_time = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2B = None
def _get_struct_2B():
    global _struct_2B
    if _struct_2B is None:
        _struct_2B = struct.Struct("<2B")
    return _struct_2B
