#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#
#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#
PROJECT_NAME := mqtt_tcp
#EXTRA_COMPONENT_DIRS += $(PROJECT_PATH)/../../../
EXTRA_COMPONENT_DIRS += ./components
CXXFLAGS += -std=c++11

include $(IDF_PATH)/make/project.mk
